acl wybrani {
    212.191.70.117;
    127.0.0.1/24;
    localhost;
};

options {
    listen-on port 53 { 127.0.0.1; 212.191.70.117; };
    listen-on-v6 port 53 { ::1; };

    directory "/var/named";

    dump-file "/var/named/data/cache_dump.db";
    statistics-file "/var/named/data/named_stats.txt";
    memstatistics-file "/var/named/data/named_mem_stats.txt";

    allow-query { localhost; wybrani; };

    forward only;
    forwarders { 212.191.64.10; };

    recursion yes;
};

zone "uni.lodz.pl" IN {
    type master;
    allow-query { wybrani; };
    file "zones/named.uni";
};

zone "2.0.10.in-addr.arpa" IN {
    type master;
    allow-query { wybrani; };
    file "zones/named.reverse";
};

controls {
    inet 127.0.0.1 port 953
    allow { 127.0.0.1; } keys { "rndckey"; };
};

include "rndc.conf";
